import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "KICKS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`text-[#212321] bg-[#E7E7E3] min-h-screen font-rubik ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative w-full py-4 bg-black overflow-hidden">
          <div className="flex whitespace-nowrap animate-marquee">
            <div className="flex gap-16 text-white uppercase font-semibold text-xs tracking-wide">
              <span>Buy 3 T-Shirts & Get 20% Off</span>
              <span>•</span>
              <span>Free Shipping Across Globe</span>
              <span>•</span>
              <span>COD Available</span>
              <span>•</span>
              <span>Buy 3 T-Shirts & Get 20% Off</span>
              <span>•</span>
              <span>Free Shipping Across Globe</span>
              <span>•</span>
              <span>COD Available</span>
            </div>
          </div>
        </div>
        <div className=" md:pt-5 pb-5">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
